# navigation
[nav]
home = "Home"
archive = "Archive"
about = "About"
source = "Source"

# about post
[post]
list = "All Posts"
archive = "Archives"
tag = "Tags"
readmore = "Read More"

# about pagination
[pager]
prev = "Prev"
next = "Next"