[meta]
title = "PuGo"
subtitle = "Static Site Generator"
keyword = "pugo,golang,static,site,generator"
desc = "pugo is a simple static site generator"
domain = "pugo.io"
root = "http://pugo.io/"
lang = "en"

[[nav]]
link = "/guide"
title = "Guide"
i18n = "guide"
hover = "guide"

[[nav]]
link = "/docs"
title = "Docs"
i18n = "docs"
hover = "docs"

[[nav]]
link = "/showcases"
title = "Showcases"
i18n = "showcases"
hover = "showcases"

[[nav]]
link = "https://github.com/go-xiaohei/pugo"
title = "Github"
i18n = "github"
icon = "fa fa-github"
blank = true

[[author]]
name = "pugo"
email = ""
url = "http://pugo.io"
bio = "the robot of pugo, who generates all default contents."

[comment]
disqus = "fuxiaohei"
duoshuo = ""

[analytics]
google = ""
baidu = ""

