
# navigation
[nav]
"guide" = "Guide"
"docs" = "Docs"
"showcases" = "Showcases"
"github" = "Github"

#footer
[footer]
"language" = "Language"
"release-notes" = "Release Notes"
"nav" = "Everything in PuGo"

#index
[index]
slogan = "easy Write, fast Build, smart Deploy"

#guide
[guide]
guide = "Guide"